'use client';
import {Clock,Heart,ChefHat,Leaf,Users,ShoppingBasket,Plus,Search,Check,Lightbulb} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {useApp} from '@/lib/app-context';
import {recipeCost,money} from '@/lib/planner';
import type {Recipe} from '@/lib/catalog';
export function PageHeading({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:React.ReactNode}){return <div className="page-heading"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p className="page-description">{description}</p>}</div>{actions&&<div className="heading-actions">{actions}</div>}</div>;}
export function EmptyState({icon:Icon=Leaf,title,text,action}:{icon?:typeof Leaf;title:string;text:string;action?:React.ReactNode}){return <div className="empty-state"><span className="empty-icon"><Icon size={28}/></span><h3>{title}</h3><p>{text}</p>{action}</div>;}
export function Pick({value,onChange,values,label}:{value:string;onChange:(v:string)=>void;values:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="pick" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v.value} value={v.value}>{v.label}</SelectItem>)}</SelectContent></Select>;}
export function SearchBox({value,onChange,placeholder='Rechercher une recette'}:{value:string;onChange:(value:string)=>void;placeholder?:string}){return <div className="search-box"><Search size={18}/><Input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></div>;}
export function RecipeCard({recipe,onPick,pickLabel,compact=false}:{recipe:Recipe;onPick?:()=>void;pickLabel?:string;compact?:boolean}){const a=useApp();const favorite=a.state.favorites.includes(recipe.id);return <article className={`recipe-card ${compact?'compact':''}`}>
 <div className={`recipe-visual visual-${recipe.category==='Pâtes'?'pasta':recipe.category==='Bols'?'bowl':recipe.category==='Salades'?'salad':'pot'}`}><button className="visual-link" onClick={()=>a.openRecipe(recipe.id)} aria-label={`Voir ${recipe.title}`}>{recipe.image?<img src={recipe.image} alt={recipe.title} loading="lazy"/>:<span className="recipe-symbol"><ChefHat size={38}/><span>{recipe.category}</span></span>}</button><span className="food-tag"><Leaf size={12}/>100 % végétal</span><Button variant="ghost" size="icon" className={`favorite-button ${favorite?'is-favorite':''}`} aria-label={`${favorite?'Retirer des favoris':'Ajouter aux favoris'} : ${recipe.title}`} onClick={()=>a.commit(s=>({...s,favorites:favorite?s.favorites.filter(id=>id!==recipe.id):[...s.favorites,recipe.id]}),favorite?'Recette retirée des favoris.':'Recette ajoutée aux favoris.')}><Heart size={18} fill={favorite?'currentColor':'none'}/></Button></div>
 <div className="recipe-info"><div className="recipe-meta"><span><Clock size={14}/>{recipe.minutes} min</span><span>{recipe.difficulty}</span></div><button className="recipe-title" onClick={()=>a.openRecipe(recipe.id)}><h3>{recipe.title}</h3></button><div className="recipe-card-bottom"><span className="recipe-price">{money(recipeCost(recipe,2,a.state.prices,a.catalog.ingredients)/2)}<small>/ portion estimée</small></span>{onPick&&<Button className="btn small secondary" onClick={onPick}>{pickLabel??'Choisir'}</Button>}</div></div>
 </article>;}
export function BudgetCard(){const a=useApp();const cost=a.items.reduce((s,i)=>s+i.purchaseCost,0),used=a.items.reduce((s,i)=>s+i.usedCost,0);const budget=a.state.profile.budget;const ratio=Math.min(100,cost/budget*100);return <section className="budget-card"><div className="card-heading"><span><ShoppingBasket size={18}/>Votre panier</span><span className="small-pill">Estimation</span></div><div className="budget-amount">{money(cost)}<span>sur {money(budget)}</span></div><div className={`budget-track ${cost>budget?'over':''}`}><span style={{width:`${ratio}%`}}/></div><p className={`budget-status ${cost>budget?'text-alert':''}`}>{cost>budget?`${money(cost-budget)} au-dessus du budget`:`${money(budget-cost)} de marge estimée`}</p><div className="budget-detail"><span>Ingrédients utilisés</span><strong>{money(used)}</strong></div><p className="fine-print">Le panier comprend les paquets entiers à acheter. Les prix sont indicatifs et modifiables.</p><Button className="btn secondary full" onClick={()=>a.navigate('courses')}>Voir ma liste de courses</Button></section>;}
export function TipCard({title,children}:{title:string;children:React.ReactNode}){return <div className="tip-card"><Lightbulb size={20}/><div><strong>{title}</strong><p>{children}</p></div></div>;}
