'use client';
import {Clock,Heart,ChefHat,Leaf,Users,ShoppingBasket,Plus,Search,Check,Lightbulb} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {useApp} from '@/lib/app-context';
import {recipeCost,money,weeklyBudget} from '@/lib/planner';
import type {Recipe} from '@/lib/catalog';
export function PageHeading({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:React.ReactNode}){return <div className="page-heading"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p className="page-description">{description}</p>}</div>{actions&&<div className="heading-actions">{actions}</div>}</div>;}
export function EmptyState({icon:Icon=Leaf,title,text,action}:{icon?:typeof Leaf;title:string;text:string;action?:React.ReactNode}){return <div className="empty-state"><span className="empty-icon"><Icon size={28}/></span><h3>{title}</h3><p>{text}</p>{action}</div>;}
export function Pick({value,onChange,values,label}:{value:string;onChange:(v:string)=>void;values:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="pick" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v.value} value={v.value}>{v.label}</SelectItem>)}</SelectContent></Select>;}
export function SearchBox({value,onChange,placeholder='Rechercher une recette'}:{value:string;onChange:(value:string)=>void;placeholder?:string}){return <div className="search-box"><Search size={18}/><Input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></div>;}
export function RecipePhoto({recipe}:{recipe:Recipe}){const t=recipe.imageTile;if(!recipe.image)return <span className="recipe-symbol"><ChefHat size={38}/><span>{recipe.category}</span></span>;return t?<span className="atlas-photo" role="img" aria-label={`Suggestion de présentation : ${recipe.title}`} style={{backgroundImage:`url(${recipe.image})`,backgroundSize:`${t.columns*100}% ${t.rows*100}%`,backgroundPosition:`${t.columns===1?0:t.column/(t.columns-1)*100}% ${t.rows===1?0:t.row/(t.rows-1)*100}%`}}/>:<img src={recipe.image} alt={`Suggestion de présentation : ${recipe.title}`} loading="lazy"/>;}
export function RecipeCard({recipe,onPick,pickLabel,compact=false}:{recipe:Recipe;onPick?:()=>void;pickLabel?:string;compact?:boolean}){const a=useApp();const favorite=a.state.favorites.includes(recipe.id);return <article className={`recipe-card ${compact?'compact':''}`}>
 <div className={`recipe-visual visual-${recipe.category==='Pâtes'?'pasta':recipe.category==='Bols'?'bowl':recipe.category==='Salades'?'salad':'pot'}`}><button className="visual-link" onClick={()=>a.openRecipe(recipe.id)} aria-label={`Voir ${recipe.title}`}><RecipePhoto recipe={recipe}/></button><span className="food-tag"><Leaf size={12}/>100 % végétal</span><Button variant="ghost" size="icon" className={`favorite-button ${favorite?'is-favorite':''}`} aria-label={`${favorite?'Retirer des favoris':'Ajouter aux favoris'} : ${recipe.title}`} onClick={()=>a.commit(s=>({...s,favorites:favorite?s.favorites.filter(id=>id!==recipe.id):[...s.favorites,recipe.id]}),favorite?'Recette retirée des favoris.':'Recette ajoutée aux favoris.')}><Heart size={18} fill={favorite?'currentColor':'none'}/></Button></div>
 <div className="recipe-info"><div className="recipe-meta"><span><Clock size={14}/>{recipe.minutes} min</span><span>{recipe.difficulty}</span></div><button className="recipe-title" onClick={()=>a.openRecipe(recipe.id)}><h3>{recipe.title}</h3></button><div className="recipe-card-bottom"><span className="recipe-price">{money(recipeCost(recipe,2,a.state.prices,a.catalog.ingredients,a.state.packSizes)/2)}<small>/ portion estimée</small></span>{onPick&&<Button className="btn small secondary" onClick={onPick}>{pickLabel??'Choisir'}</Button>}</div></div>
 </article>;}
export function BudgetCard(){const a=useApp(),b=weeklyBudget(a.state,a.activePlan,a.items);return <section className="budget-card"><div className="card-heading"><span><ShoppingBasket size={18}/>Budget des dîners</span><span className="small-pill">Prévision</span></div><div className="budget-amount">{money(b.forecast)}<span>sur {money(b.budget)}</span></div><div className={`budget-track ${b.margin<0?'over':''}`}><span style={{width:`${Math.min(100,b.forecast/b.budget*100)}%`}}/></div><p className={`budget-status ${b.margin<0?'text-alert':''}`}>{b.margin<0?`${money(-b.margin)} au-dessus du budget`:`${money(b.margin)} encore disponibles`}</p><div className="budget-detail"><span>Achats enregistrés</span><strong>{money(b.spent)}</strong></div><div className="budget-detail"><span>Reste à acheter (estimé)</span><strong>{money(b.remaining)}</strong></div><p className="fine-print">Achats enregistrés + paquets restant à acheter. Prix de simulation : adaptez les prix et formats à votre magasin. Déjeuners et petits-déjeuners exclus.</p><Button className="btn secondary full" onClick={()=>a.navigate('courses')}>Voir les courses et dépenses</Button></section>;}
export function BudgetAlert(){const a=useApp(),b=weeklyBudget(a.state,a.activePlan,a.items);if(b.margin>=0)return null;const alreadySpent=b.spent>b.budget;return <section className="budget-alert" role="status"><div><strong>{money(-b.margin)} au-dessus de votre budget de dîners</strong><p>{alreadySpent?`Vos achats enregistrés atteignent déjà ${money(b.spent)}. Modifier les menus ne retire pas ces dépenses.`:'Le panier comprend les paquets entiers. Choisissez une piste pour réduire les achats restants.'}</p></div><div className="budget-alert-actions">{alreadySpent?<Button className="btn small secondary" onClick={()=>a.navigate('courses')}>Vérifier les montants payés</Button>:<><Button className="btn small secondary" onClick={()=>a.navigate('placard')}>Ajouter ce que je possède</Button><Button className="btn small secondary" onClick={()=>{if(a.commit(s=>({...s,profile:{...s.profile,repeatMeals:true}})))a.generate();}}>Accepter deux repas identiques</Button></>}<Button className="btn small secondary" onClick={a.openPreferences}>Ajuster les jours ou le budget</Button></div></section>;}
export function TipCard({title,children}:{title:string;children:React.ReactNode}){return <div className="tip-card"><Lightbulb size={20}/><div><strong>{title}</strong><p>{children}</p></div></div>;}
