'use client';
import {useState} from 'react';
import {CalendarDays,RefreshCw,SlidersHorizontal,Clock,Users,Lock,LockOpen,Check,ChefHat,History,Plus,ChevronLeft,ChevronRight,ShoppingBasket,Leaf,BookOpen,Heart} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';
import {useApp} from '@/lib/app-context';
import {money,recipeCost,addDay,monday,totals} from '@/lib/planner';
import {PageHeading,RecipeCard,BudgetCard,TipCard,EmptyState} from './common';
export function Dashboard(){const a=useApp(),profile=a.state.profile;const total=totals(a.items);const done=a.activePlan.entries.filter(e=>e.cooked).length;const favorites=a.allRecipes.filter(r=>a.state.favorites.includes(r.id));return <>
 <PageHeading eyebrow="La cuisine végétale, au quotidien" title={profile.nickname?`Bonjour ${profile.nickname.split(' ')[0]} !`:'On mange quoi cette semaine ?'} description="Des idées simples. Un panier organisé. Plus de place pour le plaisir." actions={<Button className="btn secondary" onClick={a.openPreferences}><SlidersHorizontal size={17}/>Mes préférences</Button>}/>
 <section className="welcome-band"><div><span className="eyebrow">Votre semaine à portée de main</span><h2>Bien manger végétal.<br/><em>Garder son budget.</em></h2><p>{profile.mealCount} dîners pour {profile.people} {profile.people>1?'personnes':'personne'}, avec les ingrédients que vous avez déjà.</p><Button className="btn lime" onClick={()=>a.navigate('menus')}><CalendarDays size={18}/>Ouvrir mon planning</Button></div><div className="welcome-image"><img src="/images/curry.jpg" alt="Suggestion de présentation d’un curry de lentilles corail avec du riz"/><span className="image-note">Suggestion de présentation</span></div></section>
 <div className="stat-grid"><article><span className="stat-icon"><ShoppingBasket/></span><div><span>Panier à acheter</span><strong>{money(total.purchase)}</strong><small>Estimation pour votre planning</small></div></article><article><span className="stat-icon"><Users/></span><div><span>Repas prévus</span><strong>{a.activePlan.entries.length} dîners</strong><small>{profile.people} {profile.people>1?'personnes':'personne'}</small></div></article><article><span className="stat-icon"><ChefHat/></span><div><span>Repas préparés</span><strong>{done} / {a.activePlan.entries.length}</strong><small>Votre progression de la semaine</small></div></article></div>
 <div className="content-and-aside"><section><div className="section-heading"><div><p className="eyebrow">Du goût, simplement</p><h2>À votre menu</h2></div><Button variant="ghost" className="text-button" onClick={()=>a.navigate('menus')}>Tout le planning</Button></div><div className="recipe-grid dashboard-recipes">{a.activePlan.entries.slice(0,3).map(e=>{const r=a.allRecipes.find(r=>r.id===e.recipeId);return r?<RecipeCard key={e.id} recipe={r}/>:null;})}</div><TipCard title="Le bon réflexe avant les courses">Ajoutez le riz, l’huile et les épices que vous possédez dans votre placard : ils seront déduits des achats.</TipCard><div className="section-heading"><h2>{favorites.length?'Vos recettes préférées':'À découvrir aussi'}</h2><Button variant="ghost" className="text-button" onClick={()=>a.navigate('recettes')}>Parcourir les recettes</Button></div><div className="recipe-grid dashboard-recipes">{(favorites.length?favorites:a.catalog.recipes.filter(r=>r.image)).slice(0,3).map(r=><RecipeCard key={r.id} recipe={r}/>)}</div></section><aside><BudgetCard/><section className="club-invite"><span className="small-pill">Le club VégéBudget</span><h3>On avance mieux<br/>ensemble.</h3><p>Une assiette à partager, une question à poser ou une bonne affaire à transmettre.</p><Button className="btn secondary full" onClick={()=>a.navigate('club')}>Découvrir le club</Button></section></aside></div>
 </>;}
export function Menus(){const a=useApp();const [history,setHistory]=useState(false);const plan=a.activePlan;const saved=a.state.plans.some(p=>p.id===plan.id);const total=totals(a.items);const cooked=plan.entries.filter(e=>e.cooked).length;return <>
 <PageHeading eyebrow="Votre organisation" title="Mes menus" description="Composez la semaine à votre rythme. Les courses se recalculent avec chaque changement." actions={<><Button className="btn secondary" onClick={()=>setHistory(!history)}><History size={17}/>{history?'Masquer':'Historique'}</Button><Button className="btn primary" onClick={a.generate} disabled={!a.loaded||a.busy}><RefreshCw size={17}/>Composer ma semaine</Button></>}/>
 <div className="planning-toolbar"><div className="week-control"><Button variant="ghost" size="icon" aria-label="Semaine précédente" onClick={()=>a.setWeek(addDay(a.week,-7))}><ChevronLeft size={18}/></Button><span><CalendarDays size={17}/>Semaine du {new Date(`${a.week}T12:00:00`).toLocaleDateString('fr-FR',{day:'numeric',month:'long'})}</span><Button variant="ghost" size="icon" aria-label="Semaine suivante" onClick={()=>a.setWeek(addDay(a.week,7))}><ChevronRight size={18}/></Button></div><div className="planning-summary"><span><Users size={16}/>{a.state.profile.people} personnes</span><span><Clock size={16}/>{a.state.profile.maxMinutes} min max</span><Button variant="ghost" className="text-button" onClick={a.openPreferences}>Modifier</Button></div></div>
 {history&&<section className="history-strip">{a.state.plans.length?a.state.plans.slice().reverse().map(p=><Button key={p.id} className={`btn ${p.id===plan.id?'primary':'secondary'}`} onClick={()=>{a.setWeek(p.weekStart);a.commit(s=>({...s,activePlanId:p.id}));}}>{p.name}</Button>):<p>Votre première semaine enregistrée apparaîtra ici.</p>}</section>}
 {!saved&&<div className="information-row"><Leaf size={18}/><p>Voici une proposition adaptée à vos préférences. Vous pouvez la modifier puis la conserver.</p><Button className="btn small secondary" onClick={()=>a.modifyPlan(p=>({...p}),'Planning enregistré.')}>Conserver ce planning</Button></div>}
 <div className="content-and-aside"><section className="meal-list">{plan.entries.map((e,index)=>{const r=a.allRecipes.find(r=>r.id===e.recipeId);if(!r)return null;return <article className={`meal-row ${e.cooked?'meal-cooked':''}`} key={e.id}><div className="meal-day"><span>{new Date(`${e.date}T12:00:00`).toLocaleDateString('fr-FR',{weekday:'short'})}</span><strong>{new Date(`${e.date}T12:00:00`).getDate()}</strong></div><button className={`meal-photo ${r.image?'':'no-photo'}`} onClick={()=>a.openRecipe(r.id)} aria-label={`Voir ${r.title}`}>{r.image?<img src={r.image} alt="" loading="lazy"/>:<ChefHat size={30}/>}</button><div className="meal-copy"><span className="eyebrow">Dîner {index+1}</span><button onClick={()=>a.openRecipe(r.id)}><h3>{r.title}</h3></button><p><span><Clock size={14}/>{r.minutes} min</span><span>{money(recipeCost(r,e.servings,a.state.prices,a.catalog.ingredients)/e.servings)} / portion estimée</span></p></div><div className="meal-actions"><Button variant="ghost" size="icon" title={e.locked?'Autoriser le remplacement':'Conserver lors de la génération'} aria-label={`${e.locked?'Déverrouiller':'Conserver'} : ${r.title}`} onClick={()=>a.modifyPlan(p=>({...p,entries:p.entries.map(x=>x.id===e.id?{...x,locked:!x.locked}:x)}))}>{e.locked?<Lock size={17}/>:<LockOpen size={17}/>}</Button><Button className="btn small secondary" onClick={()=>a.replaceEntry(e)}><RefreshCw size={14}/>Changer</Button><Button className={`btn small ${e.cooked?'success':'secondary'}`} onClick={()=>a.modifyPlan(p=>({...p,entries:p.entries.map(x=>x.id===e.id?{...x,cooked:!x.cooked}:x)}),e.cooked?'Repas remis à préparer.':'Bravo, un repas préparé !')}><Check size={15}/>{e.cooked?'Préparé':'J’ai cuisiné'}</Button></div></article>;})}<div className="progress-panel"><div><strong>{cooked} repas préparés sur {plan.entries.length}</strong><span>Chaque repas compte.</span></div><Progress value={plan.entries.length?cooked/plan.entries.length*100:0}/></div><TipCard title="Un repas que vous voulez garder ?">Le cadenas conserve le plat au moment de recomposer la semaine. Vous pouvez toujours le changer vous-même.</TipCard></section><aside><BudgetCard/>{total.purchase>a.state.profile.budget&&<div className="warning-card">Le panier dépasse le budget prévu. Ajustez les repas, les prix ou le contenu de votre placard.</div>}<section className="aside-card"><h3>Envie d’un plat précis ?</h3><p>Choisissez-le dans les recettes, puis ajoutez-le à une journée du planning.</p><Button className="btn secondary full" onClick={()=>a.navigate('recettes')}><BookOpen size={17}/>Voir les recettes</Button></section></aside></div>
 </>;}
