'use client';
import {useMemo,useState} from 'react';
import {Heart,SlidersHorizontal,Search,Leaf} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {categories} from '@/lib/catalog';
import {useApp} from '@/lib/app-context';
import {isEligible,recipeCost} from '@/lib/planner';
import {PageHeading,RecipeCard,SearchBox,Pick,EmptyState} from './common';
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function Recipes(){const a=useApp();const [query,setQuery]=useState(''),[category,setCategory]=useState('Toutes'),[sort,setSort]=useState('suggestions'),[tab,setTab]=useState('all'),[compatible,setCompatible]=useState(false);
 const list=useMemo(()=>a.catalog.recipes.filter(r=>(category==='Toutes'||r.category===category)&&(tab!=='favorites'||a.state.favorites.includes(r.id))&&(!compatible||isEligible(r,a.state.profile,a.catalog.ingredients))&&normalize([r.title,r.description,...r.ingredients.map(x=>a.catalog.ingredients.find(i=>i.id===x.id)?.name??'')].join(' ')).includes(normalize(query))).sort((x,y)=>sort==='price'?recipeCost(x,2,a.state.prices,a.catalog.ingredients,a.state.packSizes)-recipeCost(y,2,a.state.prices,a.catalog.ingredients,a.state.packSizes):sort==='time'?x.minutes-y.minutes:Number(!!y.image)-Number(!!x.image)),[a.catalog,a.state,query,category,sort,tab,compatible]);
 return <><PageHeading eyebrow="Votre carnet de cuisine" title="Des recettes qui font envie" description="Des ingrédients accessibles, des étapes claires et un coût estimé par portion." actions={<Button className="btn secondary" onClick={a.openPreferences}><SlidersHorizontal size={17}/>Mes préférences</Button>}/><div className="recipe-filters"><SearchBox value={query} onChange={setQuery}/><Pick value={sort} onChange={setSort} label="Trier les recettes" values={[{value:'suggestions',label:'À découvrir'},{value:'price',label:'Prix croissant'},{value:'time',label:'Les plus rapides'}]}/></div><div className="recipe-tabs-row"><Tabs value={tab} onValueChange={setTab}><TabsList className="pill-tabs"><TabsTrigger value="all">Toutes les recettes</TabsTrigger><TabsTrigger value="favorites"><Heart size={15}/>Mes favoris ({a.state.favorites.length})</TabsTrigger></TabsList></Tabs><label className="checkbox-label"><Checkbox checked={compatible} onCheckedChange={v=>setCompatible(v===true)}/>Respecter mes préférences</label></div><div className="category-chips" aria-label="Catégories de recettes">{categories.map(c=><Button key={c} className={`category-chip ${c===category?'selected':''}`} variant="ghost" onClick={()=>setCategory(c)}>{c}</Button>)}</div><div className="results-line"><span>{list.length} {list.length>1?'recettes disponibles':'recette disponible'}</span><span><Leaf size={14}/>Entièrement végétal</span></div>{list.length?<div className="recipe-grid catalog-grid">{list.map(r=><RecipeCard key={r.id} recipe={r} onPick={()=>a.replaceEntry({id:'new',recipeId:r.id,date:a.week,servings:a.state.profile.people,cooked:false,locked:false})} pickLabel="Au menu"/>)}</div>:<EmptyState icon={tab==='favorites'?Heart:Search} title={tab==='favorites'?'Vos favoris vous attendent':'Aucune recette trouvée'} text={tab==='favorites'?'Touchez le cœur d’une recette pour la retrouver ici.':'Essayez un autre ingrédient ou élargissez les filtres.'} action={<Button className="btn secondary" onClick={()=>{setQuery('');setCategory('Toutes');setCompatible(false);setTab('all');}}>Voir toutes les recettes</Button>}/>}</>;
}
