'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {useApp,api} from '@/lib/app-context';
import {serviceComplete,type ServiceInfo} from '@/lib/service-info';
import {toast} from 'sonner';
import {PREMIUM_PRICE_LABEL,PRICE_SOURCE} from '@/lib/pricing';
export function LegalInfo({info,billingReady}:{info:ServiceInfo;billingReady:boolean}){return <div className="legal-copy"><h3>Le service</h3><p>VégéBudget organise les dîners végétaux et leurs courses. Les autres repas ne sont pas compris dans le budget. Les recettes proposent des idées de cuisine ; elles ne constituent pas un suivi médical.</p><h3>Prix et présentation</h3><p>{PRICE_SOURCE}. Personnalisez les prix et le poids des paquets. Les visuels générés sont des suggestions de présentation.</p><h3>Éditeur et contact</h3>{info.publisher?<><p>{info.publisher}</p><p>{info.address}</p><p>{info.registration}</p></>:<p>Le service est en préouverture gratuite. Les informations commerciales de l’éditeur doivent être renseignées avant l’ouverture des paiements.</p>}{info.contactEmail&&<a href={`mailto:${info.contactEmail}`}>{info.contactEmail}</a>}<h3>Données et communauté</h3><p>Vos préférences, stocks et menus appartiennent à votre compte. Les échanges et photos du club sont accessibles aux membres connectés. Vous pouvez exporter ou supprimer vos données dans « Mon compte ». Aucun outil publicitaire n’est utilisé. Pour mesurer la fréquentation, le site compte les visites et les grandes étapes (semaine composée, clic sur une offre) sans cookie : chaque visite est rattachée à une empreinte anonyme qui change chaque jour, et aucune adresse IP n’est conservée.</p>{info.privacy&&<p className="preserve-lines">{info.privacy}</p>}<h3>Abonnement</h3><p>{billingReady?`Premium coûte ${PREMIUM_PRICE_LABEL} par mois.`+' La gestion et la résiliation sont accessibles depuis Mon compte.':'Aucun paiement n’est ouvert. La découverte des outils ne demande pas de carte bancaire.'}</p>{info.terms&&<><h3>Conditions de vente</h3><p className="preserve-lines">{info.terms}</p></>}</div>;}
export function ServiceSettings(){const a=useApp(),[info,setInfo]=useState(a.serviceInfo),[busy,setBusy]=useState(false);return <section className="account-card service-settings"><h2>Informations de l’éditeur</h2><p>Ces informations seront visibles dans « Informations & confidentialité ». Renseignez les textes adaptés à votre entreprise avant d’ouvrir les paiements.</p><div className="form-grid">{([['publisher','Nom de l’entreprise ou de l’éditeur'],['address','Adresse professionnelle'],['registration','Immatriculation et informations fiscales'],['contactEmail','Email de contact public']] as const).map(([key,label])=><label className="field full-field" key={key}>{label}<Input type={key==='contactEmail'?'email':'text'} value={info[key]} onChange={e=>setInfo({...info,[key]:e.target.value})}/></label>)}<label className="field full-field">Conditions de vente<textarea rows={8} maxLength={20000} value={info.terms} onChange={e=>setInfo({...info,terms:e.target.value})}/></label><label className="field full-field">Informations sur les données personnelles<textarea rows={6} maxLength={20000} value={info.privacy} onChange={e=>setInfo({...info,privacy:e.target.value})}/></label></div><p className="fine-print">{serviceComplete(info)?'Les champs sont renseignés. Leur contenu et les modalités commerciales restent à vérifier avant activation.':'Les abonnements restent fermés tant que les informations demandées et la connexion de paiement ne sont pas prêtes.'}</p><Button className="btn primary" disabled={busy} onClick={async()=>{setBusy(true);try{await api('service-info',{info});await a.reload();toast.success('Informations enregistrées.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}>{busy?'Enregistrement…':'Enregistrer les informations'}</Button></section>;}
