'use client';
import {useState} from 'react';
import {ShoppingBasket,Download,Printer,Copy,Check,Package,Plus,Trash2,SlidersHorizontal,CheckCheck,Leaf,CalendarDays} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {toast} from 'sonner';
import {useApp,downloadText} from '@/lib/app-context';
import {quantity,money,totals,shoppingText} from '@/lib/planner';
import {PageHeading,EmptyState,SearchBox,TipCard} from './common';
export function Shopping(){const a=useApp();const [tab,setTab]=useState('buy');const stats=totals(a.items),toBuy=a.items.filter(i=>i.missing>0),stock=a.items.filter(i=>i.inPantry>0);const items=tab==='buy'?toBuy:stock;const checked=toBuy.filter(i=>a.state.checked.includes(i.id));const groups=Array.from(new Set(items.map(i=>i.ingredient.category)));
 function storePurchases(){if(!checked.length)return; a.commit(s=>{const pantry=[...s.pantry];for(const item of checked){const previous=pantry.find(p=>p.id===item.id);if(previous)pantry[pantry.indexOf(previous)]={...previous,qty:previous.qty+item.packages*item.ingredient.pack};else pantry.push({id:item.id,qty:item.packages*item.ingredient.pack});}return {...s,pantry,checked:s.checked.filter(id=>!checked.some(i=>i.id===id))};},'Les achats cochés sont ajoutés à votre placard.');}
 function setPrice(id:string,value:string){const n=Number(value.replace(',','.'));if(!Number.isFinite(n)||n<0.01||n>1000){toast.error('Saisissez un prix entre 0,01 € et 1 000 €.');return;}a.commit(s=>({...s,prices:{...s.prices,[id]:n}}));}
 return <><PageHeading eyebrow="Prêt pour les courses" title="Ma liste de courses" description="Les ingrédients sont regroupés, les quantités adaptées et votre placard pris en compte." actions={<><Button className="btn secondary" onClick={()=>downloadText(shoppingText(a.items,a.state.checked),'vegebudget-courses.txt')}><Download size={17}/>Exporter</Button><Button className="btn secondary" onClick={()=>window.print()}><Printer size={17}/>Imprimer</Button></>}/><div className="shopping-overview"><div><span>Panier à acheter</span><strong>{money(stats.purchase)}</strong><small>Paquets entiers, prix indicatifs</small></div><div><span>Coût des ingrédients utilisés</span><strong>{money(stats.used)}</strong><small>Pour {a.activePlan.entries.length} dîners</small></div><div><span>Déjà dans votre placard</span><strong>{money(stats.pantry)}</strong><small>Valeur estimée des quantités utilisées</small></div></div><div className="shopping-toolbar"><Tabs value={tab} onValueChange={setTab}><TabsList className="pill-tabs"><TabsTrigger value="buy"><ShoppingBasket size={16}/>À acheter ({toBuy.length})</TabsTrigger><TabsTrigger value="stock"><Package size={16}/>Déjà au placard ({stock.length})</TabsTrigger></TabsList></Tabs><Button variant="ghost" className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(shoppingText(a.items,a.state.checked));toast.success('Liste copiée.');}catch{downloadText(shoppingText(a.items,a.state.checked),'vegebudget-courses.txt');}}}><Copy size={15}/>Copier la liste</Button></div>{tab==='buy'&&checked.length>0&&<div className="checked-banner"><span><CheckCheck size={18}/>{checked.length} achats cochés</span><Button className="btn small primary" onClick={storePurchases}>Ranger dans mon placard</Button></div>}
 {items.length?<div className="shopping-groups">{groups.map(group=><section key={group} className="shopping-group"><h2>{group}<span>{items.filter(i=>i.ingredient.category===group).length} ingrédients</span></h2>{items.filter(i=>i.ingredient.category===group).map(item=><div key={item.id} className={`shopping-row ${a.state.checked.includes(item.id)&&tab==='buy'?'checked':''}`}>
 {tab==='buy'?<Checkbox aria-label={`J’ai acheté ${item.ingredient.name}`} checked={a.state.checked.includes(item.id)} onCheckedChange={v=>a.commit(s=>({...s,checked:v?[...new Set([...s.checked,item.id])]:s.checked.filter(id=>id!==item.id)}))}/>:<span className="stock-check"><Check size={17}/></span>}
 <div className="shopping-item-copy"><strong>{item.ingredient.name}</strong><span>{tab==='buy'?`${item.packages} ${item.packages>1?'paquets':'paquet'} de ${quantity(item.ingredient.pack,item.ingredient.unit)}`:`${quantity(item.inPantry,item.ingredient.unit)} disponibles pour le menu`}</span><small>Besoin des recettes : {quantity(item.required,item.ingredient.unit)}{item.inPantry>0&&tab==='buy'?` · Déjà présent : ${quantity(item.inPantry,item.ingredient.unit)}`:''}</small></div>{tab==='buy'&&<><div className="price-edit"><label htmlFor={`price-${item.id}`}>Prix / paquet</label><div><Input id={`price-${item.id}`} key={`${item.id}-${a.state.prices[item.id]??item.ingredient.price}`} type="number" inputMode="decimal" min="0.01" max="1000" step="0.01" defaultValue={a.state.prices[item.id]??item.ingredient.price} onBlur={e=>{if(Number(e.target.value)!==(a.state.prices[item.id]??item.ingredient.price))setPrice(item.id,e.target.value);}}/><span>€</span></div></div><strong className="shopping-row-total">{money(item.purchaseCost)}</strong></>}
 </div>)}</section>)}</div>:<EmptyState icon={tab==='buy'?ShoppingBasket:Package} title={tab==='buy'?'Tout est déjà au placard':'Votre placard peut vous aider'} text={tab==='buy'?'Les ingrédients nécessaires sont déjà disponibles selon les quantités que vous avez saisies.':'Ajoutez vos ingrédients pour réduire les achats de la semaine.'} action={<Button className="btn secondary" onClick={()=>a.navigate('placard')}>Ouvrir mon placard</Button>}/>}
 <TipCard title="Pourquoi le panier coûte plus que les portions ?">Les recettes utilisent une partie des paquets. Votre panier comprend les paquets entiers et déduit les quantités déjà présentes. Le reste des achats peut servir à d’autres repas.</TipCard><div className="footer-actions"><Button variant="ghost" className="text-button" onClick={()=>a.commit(s=>({...s,checked:[]}),'Cases décochées.')} disabled={!a.state.checked.length}>Tout décocher</Button><Button variant="ghost" className="text-button" onClick={()=>a.commit(s=>({...s,prices:{}}),'Prix indicatifs rétablis.')} disabled={!Object.keys(a.state.prices).length}>Réinitialiser mes prix</Button></div></>;
}
export function Pantry(){const a=useApp();const [query,setQuery]=useState('');const list=a.state.pantry.filter(p=>a.catalog.ingredients.find(i=>i.id===p.id)?.name.toLowerCase().includes(query.toLowerCase()));const today=new Date().toISOString().slice(0,10);return <><PageHeading eyebrow="Moins d’achats, plus d’idées" title="Mon placard" description="Notez les ingrédients que vous possédez. Ils seront déduits automatiquement de votre liste de courses." actions={<Button className="btn primary" onClick={()=>a.openPantry()}><Plus size={17}/>Ajouter un ingrédient</Button>}/><div className="pantry-intro"><span className="stat-icon"><Package size={26}/></span><div><strong>{a.state.pantry.length} {a.state.pantry.length>1?'ingrédients disponibles':'ingrédient disponible'}</strong><p>Les quantités restent sous votre contrôle : mettez-les à jour après avoir cuisiné.</p></div><Button className="btn secondary" onClick={a.generate}><Leaf size={17}/>Composer avec mon placard</Button></div><SearchBox value={query} onChange={setQuery} placeholder="Rechercher dans mon placard"/>{list.length?<div className="pantry-table"><Table><TableHeader><TableRow><TableHead>Ingrédient</TableHead><TableHead>Quantité</TableHead><TableHead>Rappel d’utilisation</TableHead><TableHead><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{list.map(p=>{const i=a.catalog.ingredients.find(i=>i.id===p.id);if(!i)return null;return <TableRow key={p.id}><TableCell><strong>{i.name}</strong><small className="cell-subtitle">{i.category}</small></TableCell><TableCell>{quantity(p.qty,i.unit)}</TableCell><TableCell>{p.expiry?<span className={p.expiry<=today?'reminder-soon':''}><CalendarDays size={14}/>{new Date(`${p.expiry}T12:00:00`).toLocaleDateString('fr-FR',{day:'numeric',month:'short'})}{p.expiry<=today?' · À vérifier':''}</span>:<span className="muted">Aucun rappel</span>}</TableCell><TableCell><div className="table-actions"><Button variant="ghost" className="text-button" onClick={()=>a.openPantry(p)}>Modifier</Button><Button variant="ghost" size="icon" aria-label={`Retirer ${i.name} du placard`} onClick={()=>a.commit(s=>({...s,pantry:s.pantry.filter(x=>x.id!==p.id)}),'Ingrédient retiré.')}><Trash2 size={16}/></Button></div></TableCell></TableRow>;})}</TableBody></Table></div>:<EmptyState icon={Package} title={query?'Aucun ingrédient trouvé':'Un petit inventaire change les courses'} text="Commencez par le riz, les pâtes, les conserves, l’huile et les épices que vous possédez déjà." action={<Button className="btn primary" onClick={()=>a.openPantry()}><Plus size={16}/>Ajouter mon premier ingrédient</Button>}/>}<TipCard title="Le rappel vous aide à vous organiser">La date saisie est un rappel personnel. Vérifiez les indications de conservation et les dates figurant sur vos produits avant de les utiliser.</TipCard></>;
}
