export type Ingredient = { id: string; name: string; category: string; unit: 'g' | 'ml' | 'pièce'; pack: number; price: number; allergens: string[] };
export type Recipe = { id: string; title: string; description: string; minutes: number; category: string; difficulty: string; image?: string; ingredients: { id: string; qty: number }[]; steps: string[]; tip: string; tags: string[] };
const i = (id: string, name: string, category: string, unit: Ingredient['unit'], pack: number, price: number, allergens: string[] = []): Ingredient => ({ id, name, category, unit, pack, price, allergens });
// Prix de simulation modifiables : il ne s'agit pas de relevés de prix magasin.
export const ingredients: Ingredient[] = [
  i('rice','Riz','Féculents','g',1000,1.85), i('pasta','Pâtes','Féculents','g',500,0.95,['Gluten']), i('couscous','Semoule','Féculents','g',500,1.15,['Gluten']), i('oats','Flocons d’avoine','Féculents','g',500,1.45,['Gluten']), i('flour','Farine de blé','Féculents','g',1000,0.95,['Gluten']), i('noodles','Nouilles de riz','Féculents','g',250,1.80), i('bread','Pain','Féculents','g',250,0.95,['Gluten']), i('wrap','Tortillas','Féculents','pièce',6,1.75,['Gluten']),
  i('red-lentils','Lentilles corail sèches','Légumineuses','g',500,1.90), i('green-lentils','Lentilles vertes sèches','Légumineuses','g',500,1.60), i('chickpeas','Pois chiches cuits, égouttés','Légumineuses','g',240,0.80), i('kidney','Haricots rouges cuits, égouttés','Légumineuses','g',250,0.85), i('white-beans','Haricots blancs cuits, égouttés','Légumineuses','g',250,0.90), i('tofu','Tofu nature','Légumineuses','g',200,1.80,['Soja']),
  i('carrot','Carottes','Fruits et légumes','g',1000,1.40), i('potato','Pommes de terre','Fruits et légumes','g',1000,1.60), i('zucchini','Courgettes','Fruits et légumes','g',1000,2.00), i('onion','Oignons','Fruits et légumes','g',1000,1.50), i('garlic','Ail','Fruits et légumes','g',100,0.90), i('spinach','Épinards surgelés','Fruits et légumes','g',1000,2.20), i('peas','Petits pois surgelés','Fruits et légumes','g',1000,2.00), i('broccoli','Brocoli surgelé','Fruits et légumes','g',1000,2.50), i('mushroom','Champignons','Fruits et légumes','g',250,1.50), i('cucumber','Concombre','Fruits et légumes','pièce',1,0.90), i('lemon','Citron','Fruits et légumes','pièce',1,0.45), i('pepper','Poivron','Fruits et légumes','pièce',1,0.75), i('cabbage','Chou blanc','Fruits et légumes','g',1000,1.50), i('squash','Courge','Fruits et légumes','g',1000,2.00), i('fresh-tomato','Tomates fraîches','Fruits et légumes','g',1000,2.00), i('parsley','Persil','Fruits et légumes','g',30,0.90), i('basil','Basilic','Fruits et légumes','g',20,0.95),
  i('tomato','Tomates concassées','Épicerie','g',400,0.75), i('coconut','Lait de coco','Épicerie','ml',400,1.35), i('corn','Maïs égoutté','Épicerie','g',285,0.85), i('oil','Huile','Épicerie','ml',500,2.80), i('peanut','Beurre de cacahuète','Épicerie','g',350,2.50,['Arachides']), i('soy-sauce','Sauce soja','Épicerie','ml',250,1.60,['Soja','Gluten']), i('curry','Curry en poudre','Épicerie','g',40,1.40), i('cumin','Cumin','Épicerie','g',40,1.40), i('paprika','Paprika','Épicerie','g',40,1.30), i('salt','Sel','Épicerie','g',1000,0.60), i('black-pepper','Poivre','Épicerie','g',40,1.30), i('yogurt','Yaourt de soja nature','Épicerie','g',400,1.60,['Soja']), i('sesame','Graines de sésame','Épicerie','g',100,1.35,['Sésame']), i('mustard','Moutarde','Épicerie','g',200,0.80,['Moutarde'])
];
const items = (values: [string, number][]) => values.map(([id,qty]) => ({id,qty}));
const r = (id:string,title:string,description:string,minutes:number,category:string,values:[string,number][],steps:string[],tip:string,tags:string[],image?:string):Recipe => ({id,title,description,minutes,category,ingredients:items(values),steps,tip,tags,image,difficulty:'Facile'});
// Les quantités de chaque recette correspondent à deux portions.
export const recipes: Recipe[] = [
  r('curry-corail','Curry de lentilles corail','Un curry doux, généreux et facile à préparer.',25,'Mijotés',[['red-lentils',140],['rice',140],['tomato',200],['spinach',150],['onion',100],['coconut',100],['oil',10],['curry',4],['salt',2]],['Rincer les lentilles. Cuire le riz selon les indications du paquet.','Émincer l’oignon et le faire revenir dans l’huile pendant 3 minutes. Ajouter le curry, les tomates, les lentilles et 350 ml d’eau.','Laisser mijoter environ 15 minutes en remuant. Ajouter de l’eau si nécessaire.','Ajouter les épinards et le lait de coco. Poursuivre 5 minutes, jusqu’à ce que les lentilles et les épinards soient cuits. Saler et servir avec le riz.'],'Les épinards surgelés se dosent facilement : gardez le reste du sachet pour un autre repas.',['Sans gluten','Une casserole','À préparer en avance'],'/images/curry.jpg'),
  r('penne-pois-chiches','Penne aux pois chiches & basilic','Des pâtes, une sauce tomate et des pois chiches fondants.',20,'Pâtes',[['pasta',180],['chickpeas',240],['tomato',300],['onion',80],['garlic',6],['oil',10],['basil',5],['salt',2]],['Cuire les pâtes dans une casserole d’eau salée, selon le paquet.','Émincer l’oignon et l’ail. Les faire revenir dans l’huile pendant 4 minutes.','Ajouter les tomates et les pois chiches égouttés. Laisser mijoter 8 minutes.','Mélanger les pâtes à la sauce, avec un peu d’eau de cuisson. Ajouter le basilic juste avant de servir.'],'Le reste de basilic peut parfumer une tartine ou une salade.',['Rapide','Moins de 25 min'],'/images/pasta.jpg'),
  r('couscous-legumes','Couscous aux légumes & pois chiches','Un bol coloré qui utilise les légumes du placard.',25,'Bols',[['couscous',160],['chickpeas',240],['carrot',200],['zucchini',200],['tomato',150],['onion',80],['oil',10],['cumin',3],['parsley',5],['salt',2]],['Découper les carottes et la courgette en petits morceaux. Émincer l’oignon.','Faire revenir l’oignon dans l’huile. Ajouter les carottes, les tomates, le cumin et 200 ml d’eau. Cuire 10 minutes.','Ajouter la courgette et les pois chiches. Cuire encore 8 minutes.','Préparer la semoule selon le paquet. Servir avec les légumes et le persil.'],'La quantité de courgette peut être remplacée par de la carotte si vous en avez déjà.',['Une casserole','À préparer en avance'],'/images/couscous.jpg'),
  r('chili-haricots','Chili doux aux haricots rouges','Un plat réconfortant, avec des conserves toutes simples.',30,'Mijotés',[['kidney',250],['rice',160],['tomato',300],['corn',100],['onion',100],['pepper',1],['oil',10],['cumin',3],['paprika',3],['salt',2]],['Cuire le riz selon le paquet. Égoutter et rincer les haricots.','Faire revenir l’oignon émincé et le poivron coupé dans l’huile pendant 5 minutes.','Ajouter les épices, les tomates, les haricots et le maïs. Laisser mijoter 15 minutes, en ajoutant un peu d’eau si nécessaire.','Saler et servir avec le riz.'],'Utilisez le maïs restant dans une salade ou une tortilla.',['Sans gluten','À préparer en avance']),
  r('bolognaise-lentilles','Bolognaise de lentilles','Une sauce généreuse à partager sur des pâtes.',30,'Pâtes',[['pasta',180],['red-lentils',100],['tomato',400],['carrot',120],['onion',100],['garlic',6],['oil',10],['salt',2]],['Râper la carotte et émincer l’oignon et l’ail. Faire revenir dans l’huile 4 minutes.','Ajouter les lentilles rincées, les tomates et 250 ml d’eau. Laisser mijoter 20 minutes, jusqu’à ce que les lentilles soient tendres.','Cuire les pâtes selon le paquet.','Ajuster la sauce avec de l’eau si besoin, saler puis mélanger avec les pâtes.'],'La carotte râpée permet d’utiliser un légume un peu moins croquant.',['À préparer en avance','Une casserole']),
  r('salade-lentilles','Salade tiède de lentilles & pommes de terre','Une assiette simple, assaisonnée au citron.',35,'Salades',[['green-lentils',140],['potato',300],['carrot',120],['onion',50],['lemon',0.5],['mustard',10],['oil',15],['parsley',5],['salt',2]],['Rincer les lentilles et les cuire dans une grande quantité d’eau selon le paquet.','Couper les pommes de terre et la carotte. Les cuire à l’eau jusqu’à ce qu’elles soient tendres.','Émincer finement l’oignon. Mélanger le jus de citron, la moutarde, l’huile et le sel.','Égoutter les légumes et les lentilles, puis mélanger avec la sauce et le persil.'],'Adaptez l’assaisonnement avec les condiments déjà présents dans votre placard.',['Sans gluten','À préparer en avance']),
  r('riz-saute','Riz sauté aux petits pois','Des légumes et du riz, le tout dans une poêle.',25,'Poêlées',[['rice',160],['peas',180],['carrot',150],['onion',80],['oil',15],['soy-sauce',15]],['Cuire le riz selon les indications du paquet.','Émincer l’oignon et couper la carotte en très petits dés. Les faire revenir dans l’huile pendant 6 minutes.','Ajouter les petits pois et 3 cuillères à soupe d’eau. Couvrir et cuire 5 minutes.','Ajouter le riz et la sauce soja. Faire sauter 3 minutes en mélangeant.'],'Couper les carottes en petits dés permet de réduire leur temps de cuisson.',['Rapide','Moins de 25 min']),
  r('pois-chiches-rotis','Pommes de terre & pois chiches rôtis','Une plaque au four, peu de vaisselle.',40,'Au four',[['potato',500],['chickpeas',240],['carrot',200],['oil',20],['paprika',4],['salt',2],['yogurt',100],['lemon',0.5]],['Préchauffer le four à 200 °C. Couper les pommes de terre en petits quartiers et les carottes en fines rondelles.','Égoutter les pois chiches. Mélanger tous les légumes avec l’huile, le paprika et le sel.','Étaler sur une plaque. Cuire environ 30 minutes en remuant à mi-cuisson, jusqu’à ce que les pommes de terre soient tendres.','Mélanger le yaourt et le jus de citron. Servir avec les légumes.'],'Conservez les mêmes épices pour plusieurs recettes de la semaine.',['Au four','Sans gluten']),
  r('tofu-cacahuete','Tofu à la cacahuète & riz','Une sauce onctueuse avec seulement quelques ingrédients.',25,'Bols',[['tofu',200],['rice',160],['broccoli',250],['peanut',35],['soy-sauce',15],['oil',10],['lemon',0.5]],['Cuire le riz selon le paquet. Cuire le brocoli à l’eau ou à la vapeur.','Couper le tofu en dés, le sécher avec un linge propre et le dorer dans l’huile pendant 6 à 8 minutes.','Mélanger le beurre de cacahuète, la sauce soja, le jus de citron et 80 ml d’eau chaude.','Ajouter la sauce au tofu, réchauffer 2 minutes et servir avec le riz et le brocoli.'],'La sauce peut également assaisonner des nouilles de riz.',['Moins de 25 min']),
  r('wrap-haricots','Wraps aux haricots & maïs','Une garniture chaude, une tortilla et le repas est prêt.',20,'Express',[['wrap',4],['kidney',250],['corn',100],['tomato',150],['onion',80],['oil',10],['cumin',3],['yogurt',80]],['Faire revenir l’oignon émincé dans l’huile pendant 4 minutes.','Ajouter les haricots égouttés, le maïs, les tomates et le cumin. Cuire 7 minutes.','Réchauffer les tortillas selon le paquet.','Répartir la garniture et le yaourt de soja, puis replier les tortillas.'],'La garniture se prépare aussi avec des haricots blancs.',['Rapide','Moins de 25 min']),
  r('soupe-petits-pois','Soupe de petits pois & tartines','Une soupe veloutée avec des légumes surgelés.',25,'Soupes',[['peas',300],['potato',200],['onion',80],['oil',10],['bread',120],['salt',2]],['Émincer l’oignon, éplucher et couper les pommes de terre en petits dés.','Faire revenir l’oignon dans l’huile. Ajouter les pommes de terre et 600 ml d’eau, puis cuire 12 minutes.','Ajouter les petits pois, poursuivre 7 minutes puis mixer. Ajuster avec de l’eau et saler.','Griller le pain et servir avec la soupe.'],'Les surgelés se portionnent sans ouvrir une nouvelle conserve.',['Une casserole','Moins de 25 min']),
  r('courge-lentilles','Velouté de courge & lentilles corail','Une soupe épaisse, douce et réconfortante.',30,'Soupes',[['squash',450],['red-lentils',120],['onion',80],['oil',10],['curry',3],['salt',2]],['Éplucher la courge si sa peau n’est pas comestible, puis la couper en petits dés.','Faire revenir l’oignon émincé dans l’huile. Ajouter le curry, la courge et les lentilles rincées.','Verser 700 ml d’eau. Laisser cuire environ 20 minutes, jusqu’à ce que tout soit tendre.','Mixer, ajouter de l’eau pour obtenir la consistance souhaitée et saler.'],'Le reste de courge peut être rôti au four pour un autre repas.',['Sans gluten','Une casserole']),
  r('poelee-blanche','Haricots blancs à la tomate','Des haricots fondants dans une sauce à l’ail.',15,'Express',[['white-beans',500],['tomato',300],['garlic',6],['oil',10],['bread',120],['parsley',5],['salt',2]],['Émincer l’ail et le faire revenir dans l’huile pendant 1 minute à feu doux.','Ajouter les tomates et laisser mijoter 5 minutes.','Ajouter les haricots égouttés. Réchauffer encore 5 minutes, puis saler.','Ajouter le persil et servir avec le pain grillé.'],'Une recette pratique pour utiliser deux petites conserves déjà disponibles.',['Rapide','Moins de 25 min']),
  r('epinards-pois-chiches','Poêlée d’épinards & pois chiches','Un dîner express, servi sur du riz.',20,'Poêlées',[['chickpeas',240],['spinach',250],['rice',140],['onion',80],['oil',10],['cumin',3],['salt',2]],['Cuire le riz selon le paquet.','Faire revenir l’oignon émincé dans l’huile pendant 4 minutes.','Ajouter les épinards surgelés, le cumin et 3 cuillères à soupe d’eau. Couvrir et cuire selon le sachet.','Ajouter les pois chiches, bien réchauffer, saler et servir avec le riz.'],'La même association fonctionne avec des haricots blancs.',['Sans gluten','Rapide','Moins de 25 min']),
  r('taboule','Taboulé de pois chiches','Un repas frais avec une vinaigrette au citron.',20,'Salades',[['couscous',140],['chickpeas',240],['cucumber',0.5],['fresh-tomato',200],['lemon',1],['oil',15],['parsley',8],['salt',2]],['Préparer la semoule selon le paquet, puis l’aérer à la fourchette et la laisser tiédir.','Couper les tomates et le concombre en petits dés. Égoutter les pois chiches.','Mélanger le jus de citron, l’huile et le sel.','Assembler la semoule, les légumes, les pois chiches, le persil et la sauce.'],'La demi-portion de concombre restante peut accompagner un autre repas.',['Rapide','À préparer en avance','Moins de 25 min']),
  r('pates-champignons','Pâtes aux champignons & petits pois','Une poêlée parfumée et une sauce légère.',25,'Pâtes',[['pasta',180],['mushroom',250],['peas',100],['garlic',6],['oil',10],['yogurt',100],['salt',2],['black-pepper',1]],['Cuire les pâtes selon le paquet et ajouter les petits pois 4 minutes avant la fin. Garder un peu d’eau de cuisson.','Émincer les champignons et l’ail. Faire revenir les champignons dans l’huile jusqu’à ce qu’ils soient dorés, puis ajouter l’ail 1 minute.','Hors du feu, incorporer le yaourt et 2 cuillères à soupe d’eau de cuisson.','Ajouter les pâtes et les petits pois, mélanger, saler et poivrer.'],'Ajouter le yaourt hors du feu préserve une sauce plus homogène.',['Moins de 25 min']),
  r('galettes-lentilles','Galettes de lentilles & carottes','Des galettes à la poêle, avec une salade fraîche.',40,'Poêlées',[['green-lentils',140],['oats',60],['carrot',150],['onion',60],['oil',15],['cumin',3],['cucumber',0.5],['lemon',0.5],['salt',2]],['Cuire les lentilles selon le paquet et bien les égoutter.','Râper la carotte. Écraser les lentilles avec les flocons, la carotte, l’oignon très finement émincé, le cumin et le sel. Laisser reposer 5 minutes.','Former 6 petites galettes compactes. Cuire dans une poêle huilée 4 minutes de chaque côté.','Servir avec le concombre assaisonné au citron.'],'Les petites galettes sont plus faciles à retourner que les grandes.',['À préparer en avance']),
  r('bowl-arc-en-ciel','Bol de riz, carottes & pois chiches','Un bol généreux avec une sauce au citron.',25,'Bols',[['rice',150],['chickpeas',240],['carrot',200],['peas',150],['lemon',0.5],['oil',15],['paprika',3],['salt',2]],['Cuire le riz selon le paquet. Ajouter les petits pois 4 minutes avant la fin.','Râper une moitié des carottes et couper le reste en fines rondelles.','Faire revenir les rondelles et les pois chiches égouttés dans 10 ml d’huile avec le paprika pendant 8 minutes.','Assembler avec le riz, les carottes râpées, le jus de citron et l’huile restante. Saler.'],'Le bol permet de combiner des restes de légumes de votre placard.',['Sans gluten','Moins de 25 min']),
  r('nouilles-legumes','Nouilles de riz à la cacahuète','Une poêlée rapide et une sauce toute simple.',20,'Express',[['noodles',150],['carrot',150],['zucchini',200],['peanut',35],['soy-sauce',15],['oil',10],['lemon',0.5]],['Préparer les nouilles de riz selon le paquet.','Couper les légumes en fins bâtonnets et les faire sauter dans l’huile pendant 6 à 8 minutes.','Mélanger le beurre de cacahuète, la sauce soja, le jus de citron et 80 ml d’eau chaude.','Ajouter les nouilles et la sauce dans la poêle, puis mélanger sur feu doux pendant 2 minutes.'],'Coupez les légumes de taille similaire pour une cuisson régulière.',['Rapide','Moins de 25 min']),
  r('mijote-lentilles','Lentilles vertes aux carottes','Une casserole généreuse pour les soirées fraîches.',40,'Mijotés',[['green-lentils',170],['carrot',250],['onion',100],['potato',250],['tomato',150],['oil',10],['paprika',3],['salt',2]],['Rincer les lentilles. Couper les carottes et les pommes de terre en petits dés.','Faire revenir l’oignon émincé dans l’huile. Ajouter le paprika, les légumes, les lentilles et les tomates.','Couvrir d’eau et laisser mijoter environ 30 minutes. Ajuster avec de l’eau si nécessaire.','Vérifier que les lentilles et les pommes de terre sont tendres, puis saler.'],'La cuisson dépend des lentilles : suivez aussi le temps indiqué sur leur paquet.',['Sans gluten','Une casserole','À préparer en avance']),
  r('poelee-chou','Poêlée de chou, pommes de terre & haricots','Un repas économique avec des légumes simples.',30,'Poêlées',[['cabbage',300],['potato',350],['white-beans',250],['onion',80],['oil',15],['paprika',3],['salt',2]],['Couper les pommes de terre en dés et les précuire dans l’eau pendant 8 minutes.','Émincer le chou et l’oignon. Faire revenir l’oignon dans l’huile puis ajouter le chou et 60 ml d’eau. Couvrir 8 minutes.','Ajouter les pommes de terre égouttées, les haricots et le paprika. Cuire encore 7 minutes en mélangeant.','Vérifier la cuisson des pommes de terre et saler.'],'Un chou entier sert à plusieurs repas sans multiplier les achats.',['Sans gluten','Une casserole']),
  r('pates-brocoli','Pâtes au brocoli & citron','Un plat frais avec un légume surgelé.',20,'Pâtes',[['pasta',180],['broccoli',300],['chickpeas',120],['garlic',6],['lemon',0.5],['oil',15],['salt',2]],['Cuire les pâtes selon le paquet. Ajouter le brocoli 5 minutes avant la fin, en suivant aussi les indications du sachet.','Faire revenir l’ail émincé dans l’huile pendant 1 minute à feu doux. Ajouter les pois chiches égouttés.','Égoutter les pâtes et le brocoli en gardant un peu d’eau de cuisson.','Mélanger avec l’ail, les pois chiches, le jus de citron et 2 cuillères à soupe d’eau de cuisson. Saler.'],'Le brocoli surgelé évite d’acheter un légume entier pour une seule recette.',['Rapide','Moins de 25 min']),
  r('tartines-haricots','Tartines de haricots blancs & tomate','Un repas rapide, à compléter selon votre faim.',15,'Express',[['bread',180],['white-beans',250],['fresh-tomato',200],['lemon',0.5],['oil',10],['garlic',3],['salt',2]],['Égoutter les haricots et les écraser avec le jus de citron, l’huile, l’ail très finement haché et le sel.','Griller légèrement le pain.','Couper les tomates en petits dés.','Étaler la purée de haricots sur les tartines, ajouter les tomates et servir.'],'Utilisez les tranches de pain déjà disponibles dans votre placard.',['Rapide','Moins de 25 min']),
  r('semoule-pois','Semoule aux petits pois & carottes','Un dîner rapide avec peu d’ingrédients.',20,'Express',[['couscous',160],['peas',180],['carrot',150],['chickpeas',120],['oil',10],['cumin',3],['salt',2]],['Couper les carottes en petits dés. Les cuire dans l’eau pendant 8 minutes.','Ajouter les petits pois et poursuivre 5 minutes, puis égoutter.','Préparer la semoule selon le paquet.','Mélanger la semoule, les légumes et les pois chiches égouttés avec l’huile, le cumin et le sel. Bien réchauffer.'],'La recette utilise une demi-conserve de pois chiches : gardez l’autre moitié pour le repas suivant.',['Rapide','Moins de 25 min'])
];
export const categories = ['Toutes','Express','Bols','Mijotés','Pâtes','Salades','Poêlées','Soupes','Au four'];
export const allergenOptions = ['Gluten','Soja','Arachides','Sésame','Moutarde','Fruits à coque'];
export const challenges = [
  { id:'three-vegetal', title:'Trois dîners végétaux', description:'Préparez trois dîners végétaux cette semaine et partagez celui que vous avez préféré.', target:3, kind:'cooked' },
  { id:'pantry-first', title:'Le placard d’abord', description:'Ajoutez cinq ingrédients de votre placard avant de préparer vos courses.', target:5, kind:'pantry' },
  { id:'one-discovery', title:'Une légumineuse à découvrir', description:'Essayez une recette avec des lentilles, des pois chiches ou des haricots.', target:1, kind:'cooked' }
];
