import { ingredients as baseIngredients, recipes as baseRecipes, type Ingredient, type Recipe } from './catalog';
export type Profile = { nickname: string; people:number; budget:number; mealCount:number; maxMinutes:number; allergens:string[]; excluded:string[]; equipment:string[]; newsletter:boolean; days?:number[]; repeatMeals?:boolean; usualSpend?:number };
export type PantryItem = { id:string; qty:number; expiry?:string };
export type Entry = { id:string; recipeId:string; date:string; servings:number; cooked:boolean; locked:boolean; consumed?:{id:string;qty:number}[] };
export type Plan = { id:string; name:string; weekStart:string; entries:Entry[]; createdAt:string; budget?:number };
export type Purchase = {id:string;weekStart:string;ingredientId:string;qty:number;packages:number;packSize:number;unitPrice:number;total:number;purchasedAt:string};
export type UserState = { profile:Profile; pantry:PantryItem[]; favorites:string[]; plans:Plan[]; activePlanId:string | null; checked:string[]; checkedByWeek:Record<string,string[]>; purchases:Purchase[]; packSizes:Record<string,number>; challengeAwards:{id:string;weekStart:string;achievedAt:string}[]; joinedChallenges:string[]; completedChallenges:string[]; prices:Record<string,number>; onboardingDone:boolean };
export type ShopItem = { id:string; ingredient:Ingredient; required:number; inPantry:number; missing:number; packages:number; purchaseCost:number; usedCost:number; surplus:number };
export const defaultProfile:Profile = { nickname:'', people:2, budget:35, mealCount:5, maxMinutes:35, allergens:[], excluded:[], equipment:['Plaques','Four','Mixeur'], newsletter:false };
export const blankState = ():UserState => ({profile:{...defaultProfile,allergens:[],excluded:[],equipment:[...defaultProfile.equipment]},pantry:[],favorites:[],plans:[],activePlanId:null,checked:[],checkedByWeek:{},purchases:[],packSizes:{},challengeAwards:[],joinedChallenges:[],completedChallenges:[],prices:{},onboardingDone:false});
export const roundMoney = (n:number) => Math.round((n+Number.EPSILON)*100)/100;
export const money = (n:number) => new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n);
export function quantity(n:number,unit:Ingredient['unit']) { const fmt=(v:number)=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2}).format(v);if(unit==='g' && n>=1000) return `${fmt(n/1000)} kg`; if(unit==='ml' && n>=1000) return `${fmt(n/1000)} l`;const fraction=unit==='pièce'?({0.25:'¼',0.5:'½',0.75:'¾'} as Record<number,string>)[n]:null;return `${fraction??fmt(n)} ${unit}${unit==='pièce' && n>1 ? 's':''}`; }
export function uniqueId(){if(typeof crypto!=='undefined'&&typeof crypto.randomUUID==='function')return crypto.randomUUID();const b=new Uint8Array(16);crypto.getRandomValues(b);b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
export function portionStep(text:string,servings:number){return text.replace(/\{([\d.]+) ([^{}]+)\}/g,(_,amount,unit)=>`${new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2}).format(Number(amount)*servings/2)} ${unit}`);}
export function stepMinutes(text:string){const times=[...text.matchAll(/(\d+)(?: à (\d+))? minutes?/g)];return times.length?Number(times[0][2]??times[0][1]):5;}
export function kitchenMeasure(amount:number,unit:Ingredient['unit']){if(unit==='ml'&&amount>0&&amount<=30)return `${new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(amount/5)} c. à café (environ)`;return '';}
export function localDate(date:Date) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; }
export function monday(date = new Date()) { const x=new Date(date); x.setDate(x.getDate()-((x.getDay()+6)%7)); return localDate(x); }
export function addDay(date:string,n:number) { const d=new Date(`${date}T12:00:00`); d.setDate(d.getDate()+n); return localDate(d); }
export function isEligible(recipe:Recipe,profile:Profile,ingredients=baseIngredients) { return recipe.minutes<=profile.maxMinutes && (recipe.category==='Au four' ? profile.equipment.includes('Four') : profile.equipment.includes('Plaques')) && !(recipe.steps.some(x=>x.toLowerCase().includes('mixer')) && !profile.equipment.includes('Mixeur')) && !recipe.ingredients.some(x=>profile.excluded.includes(x.id) || ingredients.find(i=>i.id===x.id)?.allergens.some(a=>profile.allergens.includes(a))); }
export function recipeCost(recipe:Recipe,servings=2,prices:Record<string,number>={},ingredients=baseIngredients,packSizes:Record<string,number>={}) { return roundMoney(recipe.ingredients.reduce((sum,x)=>{const i=ingredients.find(v=>v.id===x.id);return sum+(i ? x.qty*(servings/2)*(prices[i.id]??i.price)/(packSizes[i.id]??i.pack):0);},0)); }
export function shopping(entries:Entry[],pantry:PantryItem[],prices:Record<string,number>={},recipes=baseRecipes,ingredients=baseIngredients,packSizes:Record<string,number>={}):ShopItem[] {
  const required:Record<string,number>={};
  for(const e of entries) { if(e.cooked)continue;const r=recipes.find(r=>r.id===e.recipeId); if(!r) continue; for(const x of r.ingredients) required[x.id]=(required[x.id]??0)+x.qty*(e.servings/2); }
  return Object.entries(required).flatMap(([id,qty])=>{const base=ingredients.find(i=>i.id===id);if(!base)return [];const ingredient={...base,pack:packSizes[id]??base.pack};const price=prices[id]??ingredient.price;const inPantry=Math.min(qty,pantry.find(p=>p.id===id)?.qty??0);const missing=Math.max(0,qty-inPantry);const packages=missing>0.000001?Math.ceil((missing-0.000001)/ingredient.pack):0;return [{id,ingredient,required:qty,inPantry,missing,packages,purchaseCost:roundMoney(packages*price),usedCost:roundMoney(qty*price/ingredient.pack),surplus:Math.max(0,packages*ingredient.pack-missing)}];}).sort((a,b)=>a.ingredient.category.localeCompare(b.ingredient.category)||a.ingredient.name.localeCompare(b.ingredient.name));
}
export function checkedForWeek(state:UserState,week:string){return state.checkedByWeek[week]??[];}
export function weeklyBudget(state:UserState,plan:Plan,items:ShopItem[]){const spent=roundMoney(state.purchases.filter(p=>p.weekStart===plan.weekStart).reduce((sum,p)=>sum+p.total,0));const remaining=totals(items).purchase;const budget=plan.budget??state.profile.budget;return {spent,remaining,forecast:roundMoney(spent+remaining),budget,margin:roundMoney(budget-spent-remaining)};}
export function recordPurchases(state:UserState,plan:Plan,items:ShopItem[],at=new Date().toISOString()):UserState{const selected=items.filter(i=>i.missing>0&&checkedForWeek(state,plan.weekStart).includes(i.id));if(!selected.length)return state;const pantry=state.pantry.map(p=>({...p}));const purchases=[...state.purchases];for(const item of selected){const qty=item.packages*item.ingredient.pack;const found=pantry.find(p=>p.id===item.id);if(found)found.qty+=qty;else pantry.push({id:item.id,qty});purchases.push({id:uniqueId(),weekStart:plan.weekStart,ingredientId:item.id,qty,packages:item.packages,packSize:item.ingredient.pack,unitPrice:roundMoney(item.purchaseCost/item.packages),total:item.purchaseCost,purchasedAt:at});}return {...state,pantry,purchases:purchases.slice(-2000),checked:[],checkedByWeek:{...state.checkedByWeek,[plan.weekStart]:[]},plans:state.plans.some(p=>p.id===plan.id)?state.plans:[...state.plans,plan].slice(-52),activePlanId:plan.id};}
export function cookMeal(state:UserState,plan:Plan,entryId:string,recipes=baseRecipes):UserState{const entry=plan.entries.find(e=>e.id===entryId);const recipe=recipes.find(r=>r.id===entry?.recipeId);if(!entry||!recipe)return state;const pantry=state.pantry.map(p=>({...p}));const consumed:{id:string;qty:number}[]=[];if(entry.cooked){for(const x of entry.consumed??[]){const p=pantry.find(p=>p.id===x.id);if(p)p.qty+=x.qty;else pantry.push({...x});}}else{for(const x of recipe.ingredients){const p=pantry.find(p=>p.id===x.id);const qty=Math.min(p?.qty??0,x.qty*entry.servings/2);if(p&&qty>0){p.qty=Math.max(0,p.qty-qty);consumed.push({id:x.id,qty});}}}const next={...plan,entries:plan.entries.map(e=>e.id===entryId?{...e,cooked:!entry.cooked,consumed:entry.cooked?[]:consumed}:e)};return {...state,pantry,plans:[...state.plans.filter(p=>p.id!==plan.id&&p.weekStart!==plan.weekStart),next].slice(-52),activePlanId:next.id,checkedByWeek:{...state.checkedByWeek,[plan.weekStart]:[]}};}
export function challengeProgress(state:UserState,plan:Plan,id:string,recipes=baseRecipes,ingredients=baseIngredients){if(id==='pantry-first')return state.pantry.filter(p=>p.qty>0).length;const cooked=plan.entries.filter(e=>e.cooked);if(id==='one-discovery')return cooked.filter(e=>recipes.find(r=>r.id===e.recipeId)?.ingredients.some(x=>['red-lentils','green-lentils','chickpeas','kidney','white-beans'].includes(x.id))).length;return cooked.length;}
export function awardChallenges(state:UserState,plan:Plan,recipes=baseRecipes,ingredients=baseIngredients):UserState{const targets:Record<string,number>={'three-vegetal':3,'pantry-first':5,'one-discovery':1};const awards=state.challengeAwards.filter(a=>a.weekStart!==plan.weekStart);for(const id of state.joinedChallenges){if(challengeProgress(state,plan,id,recipes,ingredients)>=(targets[id]??Infinity))awards.push(state.challengeAwards.find(a=>a.id===id&&a.weekStart===plan.weekStart)??{id,weekStart:plan.weekStart,achievedAt:new Date().toISOString()});}return {...state,challengeAwards:awards.slice(-156)};}
export function totals(items:ShopItem[]) { return {purchase:roundMoney(items.reduce((s,i)=>s+i.purchaseCost,0)),used:roundMoney(items.reduce((s,i)=>s+i.usedCost,0)),pantry:roundMoney(items.reduce((s,i)=>s+(i.required ? i.usedCost*i.inPantry/i.required:0),0)),packageSurplus:roundMoney(items.reduce((s,i)=>s+(i.required ? i.usedCost/i.required*i.surplus:0),0))}; }
const random = (seed:number) => {let x=seed||1;return ()=>{x=(x*1664525+1013904223)>>>0;return x/4294967296;};};
export function generatePlan(state:UserState,weekStart=monday(),seed=Date.now(),recipes=baseRecipes,ingredients=baseIngredients,locked:Entry[]=[]):{plan:Plan|null;warning:string|null} {
  const eligible=recipes.filter(r=>isEligible(r,state.profile,ingredients));
  if(!eligible.length) return {plan:null,warning:'Aucune recette ne correspond à ces préférences. Augmentez le temps disponible ou ajustez vos exclusions.'};
  const days=state.profile.days?.length?[...new Set(state.profile.days)].sort((a,b)=>a-b):Array.from({length:state.profile.mealCount},(_,day)=>day);const slots=days.length;
  const kept=locked.filter((entry,index)=>{const recipe=recipes.find(r=>r.id===entry.recipeId);return !!recipe && isEligible(recipe,state.profile,ingredients) && days.some(day=>addDay(weekStart,day)===entry.date) && locked.findIndex(e=>e.date===entry.date)===index;});
  const spent=state.purchases.filter(p=>p.weekStart===weekStart).reduce((s,p)=>s+p.total,0);
  let best:Entry[]=[];let bestScore=Infinity;const rand=random(seed);
  for(let trial=0;trial<45;trial++) {
    const selected:Entry[]=kept.map(x=>({...x,servings:state.profile.people}));
    for(let day=0;day<slots;day++) {
      const date=addDay(weekStart,days[day]);if(selected.some(e=>e.date===date))continue;
      let choices=eligible.filter(r=>selected.filter(e=>e.recipeId===r.id).length<(state.profile.repeatMeals?2:1)); if(!choices.length) choices=eligible;
      const previousCost=totals(shopping(selected,state.pantry,state.prices,recipes,ingredients,state.packSizes)).purchase;
      const scored=choices.map(r=>{const entry={id:`slot-${day}`,recipeId:r.id,date,servings:state.profile.people,cooked:false,locked:false};const cost=totals(shopping([...selected,entry],state.pantry,state.prices,recipes,ingredients,state.packSizes)).purchase;return {r,entry,score:cost-previousCost+rand()*(trial<15?1:5)+(state.favorites.includes(r.id)?-0.5:0)+selected.filter(e=>recipes.find(v=>v.id===e.recipeId)?.category===r.category).length*0.55};}).sort((a,b)=>a.score-b.score);
      selected.push(scored[0].entry);
    }
    const cost=spent+totals(shopping(selected,state.pantry,state.prices,recipes,ingredients,state.packSizes)).purchase;
    const variety=new Set(selected.map(e=>recipes.find(r=>r.id===e.recipeId)?.category)).size;
    const score=Math.max(0,cost-state.profile.budget)*1000+cost-variety*0.6;
    if(score<bestScore){bestScore=score;best=selected;}
  }
  const entries=best.sort((a,b)=>a.date.localeCompare(b.date)).map(e=>({...e,id:e.locked||e.cooked?e.id:uniqueId()}));
  const cost=spent+totals(shopping(entries,state.pantry,state.prices,recipes,ingredients,state.packSizes)).purchase;
  let warning=cost>state.profile.budget ? `Le panier estimé dépasse votre budget de ${money(cost-state.profile.budget)}. Ajoutez ce que vous avez au placard, ajustez les prix ou augmentez le budget.` : null;
  if(new Set(entries.map(e=>e.recipeId)).size<slots&&!state.profile.repeatMeals) warning=`Les préférences actuelles limitent le choix : certaines recettes se répètent.${warning?' '+warning:''}`;
  return {plan:{id:uniqueId(),name:`Semaine du ${new Date(`${weekStart}T12:00:00`).toLocaleDateString('fr-FR',{day:'numeric',month:'long'})}`,weekStart,entries,createdAt:new Date().toISOString(),budget:state.profile.budget},warning};
}
export function shoppingText(items:ShopItem[],checked:string[]) {return ['VégéBudget — ma liste de courses','Prix relevés chez Carrefour le 7 octobre 2026, à personnaliser selon votre magasin.','',...items.filter(i=>i.missing>0).map(i=>`${checked.includes(i.id)?'✓':'□'} ${i.ingredient.name} — ${i.packages} ${i.packages>1?'paquets':'paquet'} de ${quantity(i.ingredient.pack,i.ingredient.unit)} — ${money(i.purchaseCost)}`),'',`Panier estimé : ${money(totals(items).purchase)}`].join('\n');}
