import { z } from 'zod';
const finite=z.number().finite(); const id=z.string().min(1).max(120);
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const p=new Date(`${v}T12:00:00Z`);return !Number.isNaN(p.getTime())&&p.toISOString().slice(0,10)===v;},'Date invalide');
const amounts=z.record(finite.positive().max(100000)).refine(x=>Object.keys(x).length<=100);
const checkedWeeks=z.record(z.array(id).max(100)).refine(x=>Object.keys(x).length<=104&&Object.keys(x).every(k=>date.safeParse(k).success));
export const stateSchema=z.object({
 profile:z.object({nickname:z.string().trim().max(40),people:finite.int().min(1).max(8),budget:finite.min(1).max(500),mealCount:finite.int().min(1).max(7),maxMinutes:finite.int().min(15).max(90),allergens:z.array(z.enum(['Gluten','Soja','Arachides','Sésame','Moutarde','Fruits à coque'])).max(6),excluded:z.array(id).max(100),equipment:z.array(z.enum(['Plaques','Four','Mixeur'])).max(3),newsletter:z.boolean(),days:z.array(finite.int().min(0).max(6)).min(1).max(7).refine(x=>new Set(x).size===x.length).optional(),repeatMeals:z.boolean().optional(),usualSpend:finite.min(1).max(1000).optional()}),
 pantry:z.array(z.object({id,qty:finite.min(0).max(100000),expiry:date.optional()})).max(100),favorites:z.array(id).max(300),
 plans:z.array(z.object({id,name:z.string().max(120),weekStart:date,createdAt:z.string().datetime(),budget:finite.min(1).max(500).optional(),entries:z.array(z.object({id,recipeId:id,date,servings:finite.int().min(1).max(8),cooked:z.boolean(),locked:z.boolean(),consumed:z.array(z.object({id,qty:finite.min(0).max(100000)})).max(25).optional()})).max(7)})).max(52),
 activePlanId:id.nullable(),checked:z.array(id).max(100),checkedByWeek:checkedWeeks.default({}),packSizes:amounts.default({}),
 purchases:z.array(z.object({id,weekStart:date,ingredientId:id,qty:finite.positive().max(1000000),packages:finite.int().min(1).max(100000),packSize:finite.positive().max(100000),unitPrice:finite.min(0.01).max(1000),total:finite.min(0.01).max(1000000),purchasedAt:z.string().datetime()})).max(2000).default([]),
 challengeAwards:z.array(z.object({id,weekStart:date,achievedAt:z.string().datetime()})).max(156).default([]),
 joinedChallenges:z.array(id).max(20),completedChallenges:z.array(id).max(20),prices:z.record(finite.min(0.01).max(1000)).refine(x=>Object.keys(x).length<=100),onboardingDone:z.boolean()
}).transform(s=>{if(s.checked.length&&Object.keys(s.checkedByWeek).length===0){const week=s.plans.find(p=>p.id===s.activePlanId)?.weekStart;if(week)s.checkedByWeek[week]=[...s.checked];}return {...s,checked:[]};});
export const postSchema=z.object({content:z.string().trim().min(3).max(2000),category:z.enum(['Mon assiette','Bon plan','Question','Astuce']),photoId:id.optional().nullable()});
export const recipeSchema=z.object({id:id.regex(/^[a-z0-9-]+$/),title:z.string().min(3).max(100),description:z.string().min(3).max(240),minutes:finite.int().min(5).max(180),category:z.enum(['Express','Bols','Mijotés','Pâtes','Salades','Poêlées','Soupes','Au four']),difficulty:z.string().max(40),ingredients:z.array(z.object({id,qty:finite.positive().max(10000)})).min(1).max(25),steps:z.array(z.string().min(3).max(600)).min(1).max(12),tip:z.string().max(400),tags:z.array(z.string().max(40)).max(8),image:z.string().regex(/^\/images\/[a-z0-9-]+\.(jpg|png|webp)$/).optional(),imageTile:z.object({columns:finite.int().min(1).max(3),rows:finite.int().min(1).max(3),column:finite.int().min(0).max(2),row:finite.int().min(0).max(2)}).optional()});
export const serviceSchema=z.object({publisher:z.string().trim().max(120),address:z.string().trim().max(250),registration:z.string().trim().max(100),contactEmail:z.union([z.literal(''),z.string().email().max(160)]),terms:z.string().trim().max(20000),privacy:z.string().trim().max(20000)});
