import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHmac} from 'node:crypto';

// Exercise the built Worker in an isolated, temporary runtime. No deployed
// service, production database, real account or payment provider is contacted.
const require=createRequire(import.meta.url);
const requireWrangler=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=requireWrangler('miniflare');
const origin='http://terminal.local:4173';
const moduleFiles=['index.js',...readdirSync('dist/server',{recursive:true}).filter(path=>/\.(js|mjs)$/.test(path)&&path!=='index.js')];
const options={modules:moduleFiles.map(path=>({type:'ESModule',path:resolve('dist/server',path)})),modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],assets:{directory:resolve('dist/client'),routerConfig:{has_user_worker:true}},bindings:{BILLING_ENABLED:'false',SITE_ORIGIN:origin},cf:false};
const mf=new Miniflare(options);
const owner={id:'local-test-owner',email:'owner@example.invalid'};
const member={id:'local-test-member',email:'member@example.invalid'};
let checks=0;
const check=(value,expected,label)=>{assert.deepEqual(value,expected,label);checks++;};
async function request(path,user,data,headers={}){
 const auth=user?{'oai-authenticated-user-id':user.id,'oai-authenticated-user-email':user.email,'oai-authenticated-user-full-name':encodeURIComponent(user===owner?'Propriétaire test':'Membre test'),'oai-authenticated-user-full-name-encoding':'percent-encoded-utf-8'}:{};
 const response=await mf.dispatchFetch(origin+path,{method:data===undefined?'GET':'POST',headers:{...auth,...(data!==undefined?{'Content-Type':'application/json',Origin:origin}:{}),...headers},...(data!==undefined?{body:JSON.stringify(data)}:{})});
 const type=response.headers.get('Content-Type')??'';
 const body=type.includes('json')?await response.json():await response.text();
 return {status:response.status,body};
}
const api=(action,user,data)=>request('/api/app'+(data===undefined?'?action='+action:''),user,data===undefined?undefined:{action,...data});
try{
 let db=await mf.getD1Database('DB');
 const statements=readFileSync('drizzle/0000_stale_swordsman.sql','utf8').split('--> statement-breakpoint').map(x=>x.trim()).filter(Boolean);
 await db.batch(statements.map(sql=>db.prepare(sql)));
 const page=await request('/');check(page.status,200,'server render');assert.match(page.body,/VégéBudget/);checks++;
 const bootstrap=await api('bootstrap');check(bootstrap.status,200,'anonymous bootstrap');check(bootstrap.body.catalog.recipes.length,24,'initial catalogue');check(bootstrap.body.billingReady,false,'billing closed');
 check((await api('state',undefined,{state:bootstrap.body.state,revision:0})).status,401,'anonymous write blocked');
 check((await request('/api/app',undefined,null)).status,400,'null JSON rejected');
 const o=await api('bootstrap',owner);check(o.body.admin,true,'private owner administrator');
 const m=await api('bootstrap',member);check(m.body.admin,false,'other member has no administration');
 check((await api('admin',member)).status,403,'server protects administration');
 check((await request('/api/app',owner,{action:'state',state:o.body.state,revision:0},{Origin:'https://unrelated.invalid'})).status,403,'cross-origin write blocked');
 const state=structuredClone(o.body.state);state.profile.people=3;state.pantry=[{id:'rice',qty:320}];
 check((await api('state',owner,{state,revision:0})).status,200,'state saved');
 check((await api('state',owner,{state,revision:0})).status,409,'stale writes rejected');
 const back=await api('bootstrap',owner);check(back.body.state.profile.people,3,'state read back');check(back.body.revision,1,'revision advanced');check((await api('bootstrap',member)).body.state.pantry.length,0,'member data isolated');
 check((await api('state',owner,{state:{...state,profile:{...state.profile,people:0}},revision:1})).status,400,'invalid portions rejected');
 check((await api('state',owner,{state:{...state,pantry:[{id:'rice',qty:1},{id:'rice',qty:2}]},revision:1})).status,400,'duplicate pantry stock rejected');
 const boundary='vegebudget-test-multipart';const photoBody=Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="test-curry.jpg"\r\nContent-Type: image/jpeg\r\n\r\n`),readFileSync('public/images/curry.jpg'),Buffer.from(`\r\n--${boundary}--\r\n`)]);
 const photoResponse=await mf.dispatchFetch(origin+'/api/photos',{method:'POST',headers:{'oai-authenticated-user-id':owner.id,'oai-authenticated-user-email':owner.email,Origin:origin,'Content-Type':`multipart/form-data; boundary=${boundary}`},body:photoBody});
 check(photoResponse.status,201,'image upload');const photo=await photoResponse.json();
 check((await request('/api/photos/'+photo.id,member)).status,404,'unpublished photo stays private');
 check((await api('post',member,{content:'Essai de photo appartenant à un autre membre.',category:'Question',photoId:photo.id})).status,400,'photo ownership enforced');
 const posted=await api('post',owner,{content:'Mon premier dîner végétal de test.',category:'Mon assiette',photoId:photo.id});check(posted.status,201,'post persisted');const post=posted.body.id;
 check((await api('delete-post',member,{post})).status,403,'post ownership enforced');
 check((await api('comment',member,{post,content:'Une réponse de test.'})).status,201,'comment persisted');
 check((await api('like',member,{post})).body.liked,true,'like created');check((await api('like',member,{post})).body.liked,false,'like toggled');
 const posts=await api('posts',member);check(posts.body.posts.length,1,'real post listing');check(posts.body.posts[0].comment_count,1,'real comment count');
 check((await api('report',member,{post,reason:'Signalement de test.'})).status,200,'report persisted');
 check((await api('admin',owner)).body.reports.length,1,'report visible to administrator');
 check((await api('moderate',owner,{post,status:'hidden'})).status,200,'moderation persisted');check((await api('posts')).body.posts.length,0,'hidden post not listed');
 check((await request('/api/photos/'+photo.id,member)).status,404,'hidden post photo stays private');
 await api('moderate',owner,{post,status:'visible'});
 await api('waitlist',member,{});await api('waitlist',member,{});
 check((await api('admin',owner)).body.waitlist.length,1,'waitlist deduplicated');
 const exportData=await api('export',member);check(exportData.body.email,member.email,'personal export');check(exportData.body.comments.length,1,'export includes own comment');
 check((await request('/api/billing',member,{action:'checkout'})).status,503,'unconfigured payments blocked');
 check((await api('delete-post',owner,{post})).status,200,'post deleted');check((await api('comments',member,undefined)).body.comments.length,0,'comments disappear with post');
 check((await db.prepare('SELECT COUNT(*) AS n FROM comments').first()).n,0,'comment cascade');
 check((await api('catalog',member,{prices:{rice:3.4}})).status,403,'catalogue editing protected');
 await api('catalog',owner,{prices:{rice:3.4}});check((await api('bootstrap',owner)).body.catalog.ingredients.find(i=>i.id==='rice').price,3.4,'shared price persists');
 const edited={...bootstrap.body.catalog.recipes[0],title:'Curry de test'};
 check((await api('catalog',owner,{recipe:edited})).status,200,'recipe editing');check((await api('bootstrap',owner)).body.catalog.recipes.find(r=>r.id===edited.id).title,edited.title,'recipe change read back');
 await api('catalog',owner,{toggleRecipe:edited.id});check((await api('bootstrap',owner)).body.catalog.recipes.length,23,'hidden recipe excluded');
 await api('catalog',owner,{toggleRecipe:edited.id});
 await mf.setOptions({...options,bindings:{...options.bindings,BILLING_ENABLED:'true',STRIPE_SECRET_KEY:'local-test-unused',STRIPE_PRICE_ID:'local-test-unused',STRIPE_WEBHOOK_SECRET:'local-test-unused'}});
 db=await mf.getD1Database('DB');
 const event={id:'evt_local_test',type:'local.test',created:Math.floor(Date.now()/1000),data:{object:{}}};const raw=JSON.stringify(event),timestamp=event.created;
 const signature=createHmac('sha256','local-test-unused').update(`${timestamp}.${raw}`).digest('hex');
 const webhook=()=>mf.dispatchFetch(origin+'/api/billing/webhook',{method:'POST',headers:{'Content-Type':'application/json','stripe-signature':`t=${timestamp},v1=${signature}`},body:raw});
 check((await webhook()).status,200,'valid webhook signature');check((await webhook()).status,200,'webhook duplicate handled');
 check((await mf.dispatchFetch(origin+'/api/billing/webhook',{method:'POST',headers:{'Content-Type':'application/json','stripe-signature':`t=${timestamp},v1=${'0'.repeat(64)}`},body:raw})).status,400,'invalid webhook signature rejected');
 const memberState=(await api('bootstrap',member)).body.state;
 memberState.favorites=bootstrap.body.catalog.recipes.slice(0,11).map(r=>r.id);
 check((await api('state',member,{state:memberState,revision:0})).status,403,'free tier enforced on server');
 await db.prepare("UPDATE members SET subscription_status='active' WHERE id=?").bind(member.id).run();
 check((await api('state',member,{state:memberState,revision:0})).status,200,'premium limits enabled');
 check((await api('delete-account',member,{confirm:'SUPPRIMER'})).status,409,'active subscription must be cancelled before data deletion');
 await db.prepare("UPDATE members SET subscription_status='none' WHERE id=?").bind(member.id).run();
 check((await api('delete-account',member,{confirm:'SUPPRIMER'})).status,200,'member deletion');
 check((await db.prepare('SELECT COUNT(*) AS n FROM waitlist').first()).n,0,'waitlist cascade');
 console.log(`${checks} API and persistence assertions passed.`);
}finally{await mf.dispose();}
